# Kafka 설정 (community-service)
app:
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 10
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      concurrency: 2
    
    producer:
      acks: all
      retries: 3
      enable-idempotence: true
      compression-type: lz4
    
    topics:
      community-notification:
        name: community.notification
        consumer-group: community-service-group
        partitions: 3
        replication-factor: 1
      
      user-profile-changed:
        name: user.profile.changed
        consumer-group: community-service-group
        partitions: 3
        replication-factor: 1

# Spring Kafka 기본 설정 (호환성 유지용)
spring:
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap-servers}
    consumer:
      group-id: community
      auto-offset-reset: ${app.kafka.consumer.auto-offset-reset}
    producer:
      acks: ${app.kafka.producer.acks}