# Kafka Configuration for Community Service
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 10
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      enable-idempotence: true

# Community Service Kafka Topics
community:
  kafka:
    topics:
      user-profile-changed: user.profile.changed
    consumer:
      concurrency: 2
      batch-size: 10
      retry:
        attempts: 3
        backoff-ms: 1000

# Profile별 환경 설정
---
spring:
  profiles: local
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest # 로컬에서는 처음부터 읽기

---
spring:
  profiles: development
  kafka:
    bootstrap-servers: kafka-dev.aiva.internal:9092
    consumer:
      group-id: community-dev

---
spring:
  profiles: production
  kafka:
    bootstrap-servers: kafka-prod.aiva.internal:9092
    consumer:
      group-id: community-prod
      session-timeout-ms: 45000
      heartbeat-interval-ms: 15000
community:
  kafka:
    consumer:
      concurrency: 4 # 프로덕션에서 더 많은 병렬 처리