spring:
  application:
    name: chat-service
  profiles:
    active: local
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/aiva_chat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: aiva
    password: aiva123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.aiva: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key}

ai:
  server:
    base-url: ${AI_SERVER_URL:http://localhost:8080}

app:
  webclient:
    connect-timeout: 5000
    read-timeout: 10000
    services:
      user-service:
        url: ${USER_SERVICE_URL:http://localhost:8081}
        connect-timeout: 3000
        read-timeout: 5000
