spring:
  application:
    name: notification-service
  profiles:
    active: local
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/aiva_notification?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: aiva
    password: aiva123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.aiva: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

aws:
  region: ap-northeast-2
  sns:
    topic-arn: ${AWS_SNS_TOPIC_ARN:arn:aws:sns:ap-northeast-2:123456789012:aiva-notifications-dev}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:https://sqs.ap-northeast-2.amazonaws.com/123456789012/aiva-notification-queue-dev}

fcm:
  service-account-key: ${FCM_SERVICE_ACCOUNT_KEY:classpath:firebase-service-account.json}
