apiVersion: v1
kind: Namespace
metadata:
  name: aiva
  labels:
    name: aiva
    environment: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aiva-config
  namespace: aiva
data:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_USER: "aiva"
  MYSQL_PASSWORD: "aiva123"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  JWT_SECRET: "aiva-jwt-secret-key-for-k8s"
